export const BUY_ITEM = 'BUY_ITEM';
export const FETCH_ITEM_DETAILS = 'FETCH_ITEM_DETAILS';
export const RECEIVE_ITEM_DETAILS = 'RECEIVE_ITEM_DETAILS';
export const FETCH_CATALOG = 'FETCH_CATALOG';
export const RECEIVE_CATALOG = 'RECEIVE_CATALOG';
